name: DQ Sentinel

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:    # allows manual "Run workflow" from Actions UI

jobs:
  run-dq:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set PYTHONPATH to repo root
        # Export repo workspace to subsequent steps so "from src import ..." works
        run: echo "PYTHONPATH=${{ github.workspace }}" >> $GITHUB_ENV

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.x'
          check-latest: false

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # prefer binary wheels to avoid building from source on the runner
          pip install --prefer-binary -r requirements.txt || pip install -r requirements.txt
          pip install pytest

      - name: Run unit tests
        run: pytest -q

      - name: Run DQ sentinel (uses data/cleaned or sample data)
        run: |
          # Ensure cleaned data exists in the repo under data/cleaned/
          python src/dq_sentinel.py --data-dir data/cleaned --out-dir reports/ci --calendar data/calendar.csv --promos data/promos.csv --pattern "sales_weekly*.csv"

      - name: Upload reports artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: dq-reports
          path: reports/ci
